//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_full_stack
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public int Id { get; set; }
        public int SurveyId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string Barcode { get; set; }
        public string Status { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
