//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_full_stack
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveStatusHistory
    {
        public int Id { get; set; }
        public Nullable<int> MoveId { get; set; }
        public string Status { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Move Move { get; set; }
        public virtual User User { get; set; }
    }
}
