//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_full_stack
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveAssignment
    {
        public int Id { get; set; }
        public Nullable<int> MoveId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> CrewId { get; set; }
    
        public virtual Crew Crew { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Move Move { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
