//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_full_stack
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteHistory
    {
        public int Id { get; set; }
        public Nullable<int> QuoteId { get; set; }
        public Nullable<int> VersionNo { get; set; }
        public string QuoteData { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
