//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_full_stack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.MoveAssignments = new HashSet<MoveAssignment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string VehicleNumber { get; set; }
        public Nullable<decimal> CapacityWeight { get; set; }
        public Nullable<decimal> CapacityVolume { get; set; }
        public string Status { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MoveAssignment> MoveAssignments { get; set; }
    }
}
